acquit (v):
  to discharge completely (as from an accusation or obligation):
  - The Senate on Wednesday voted to acquit President Trump on impeachment charges of abuse of power and obstruction of Congress over his dealings with Ukraine, marking the beginning of the end of the months-long saga.
  to conduct (oneself) usually satisfactorily especially under stress:

all ears:
  ready and eager to listen:
  - Please tell me more about your trip to Venice,I am all ears.

aphorism (n):
  a pithy observation that contains a general truth, such as, “if it ain't broke, don't fix it.”:
  a concise statement of a scientific principle, typically by an ancient classical author.:

apostasy (n):
  the abandonment or renunciation of a religious or political belief:
  - The execution of their leader for apostasy brought widespread criticism.

apparition (n):
  a ghost or ghostlike image of a person:
  - In the village of Domremy where Joan grew up, Emil met her apparition again.
  the appearance of something remarkable or unexpected, typically an image of this type:
  - twentieth-century apparitions of the Virgin

as mad as a hatter:
  to suggest (lightheartedly) that a person is suffering from insanity.:
  - His behavior became increasingly erratic, leading people to believe he was as mad as a hatter.

at the drop of a hat:
  Without any hesitation; instantly:
  - We're expected to just do it at the drop of a hat.

beat the (living) daylights out of SB:
  to physically attack one, as with punches and other blows, such that they suffer significant injury:
  - Our neighbor is in the hospital because a burglar beat the daylights out of him.
  - I'm worried that the captain of the football team will beat the living daylights out of me if he finds out that I'm secretly seeing his girlfriend.
  - Oh, my boyfriend knows that I would beat the living daylights out of him if he ever lies to me about something that serious.
  to defeat one decisively in a competition:
  - The final score was 17-1? Wow, we really beat the living daylights out of that team!

bereft:
  deprived of or lacking something, especially a nonmaterial asset:
  - Her room was stark and bereft of color.
  \(of a person\) lonely and abandoned, especially through someone's death or departure:
  - His death in 1990 left her bereft.

bite the bullet:
  to endure something necessary but unpleasant:
  - When no painkiller was available (in makeshift battlefield tents, for example), soldiers literally had to bite down on a bullet during surgical operations.

be black balled:
  to be voted against and denied membership:

bromide:
  a commonplace or tiresome person, bore:
  a commonplace or hackneyed statement or notion:
  - In many ways, he's an outlier on the self-help circuit. Thomas isn't selling shortcuts to success or feel-good bromides. He makes achievement sound grueling. His knack is for transforming those he meets—a CEO, an NBA All-Star, a guy manning the desk at a hotel—into the sort of person who loves digging deep and grinding hard.
  - Currently, Virginia's leaders are engaged in a tax debate over standard deductions for the middle class. Studying that problem would be a bromide that induces inertia. What is needed is action.

by (or in) leaps and bounds:
  with startlingly rapid progress:
  - FiiO’s own music app has also come in leaps and bounds and I would rate it close to HiBy Music in terms of ease of use but still lacking that killer DSP app like MSEB.
  - Productivity improved in leaps and bounds.

\(win\) by the skin of one's teeth:
  by a very narrow margin; barely:
  - I felt sleep all the times because I smoke to much joint. But thanks to the registered letter, sent to God everyday by mother, I could graduate by the skin of my teeth.

carbon copy:
  an exact copy:

carry the day:
  be victorious or successful:
  - Lacking good strategy in the battle, courage won’t carry the day.

chapfallen (a):
  cast down in spirit; depressed:
  - This season or next, don't bet on them turning a profit without making the playoffs. They need to do that next year to satisfy perennially chapfallen fans, if nothing else.

clairvoyance (n):
  the supposed faculty of perceiving things or events in the future or beyond normal sensory contact:
  - She stared at the card as if she could contact its writer by clairvoyance.
  - I am not a clairvoyant so I cannot tell what will happen in the next 6 months.

close, but no cigar:
  That's almost correct, but not quite:
  - It was close but no cigar for Johnny as he came second once again.

come to pass:
  happen; occur:
  - it came to pass that she had two sons
  - It came to pass that their love for each other grew and grew.

contrite:
  feeling or expressing remorse or penitence; affected by guilt:
  - On the dying bed, he made a very careful confession of his sins with a contrite heart.

conundrum:
  a confusing and difficult problem or question:
  - This is the confidence conundrum, where in order to be happy or loved or successful, first you need to be confident; but then to be confident, first you need to be happy or loved or successful.

coup de grace (n):
  a final blow or shot given to kill a wounded person or animal:
  - He administered the coup de grâce with a knife.
  an action or event that serves as the culmination of a bad or deteriorating situation:
  - The epidemic has been the coup de grâce for the airline crisis.
