cquit (v):
  to discharge completely (as from an accusation or obligation):
  - The Senate on Wednesday voted to acquit President Trump on impeachment charges of abuse of power and obstruction of Congress over his dealings with Ukraine, marking the beginning of the end of the months-long saga.
  to conduct (oneself) usually satisfactorily especially under stress:

all ears:
  ready and eager to listen:
  - Please tell me more about your trip to Venice,I am all ears.

aphorism (n):
  a pithy observation that contains a general truth, such as, “if it ain't broke, don't fix it.”:
  a concise statement of a scientific principle, typically by an ancient classical author.:

apostasy (n):
  the abandonment or renunciation of a religious or political belief:
  - The execution of their leader for apostasy brought widespread criticism.

apparition (n):
  a ghost or ghostlike image of a person:
  - In the village of Domremy where Joan grew up, Emil met her apparition again.
  the appearance of something remarkable or unexpected, typically an image of this type:
  - twentieth-century apparitions of the Virgin

as mad as a hatter:
  to suggest (lightheartedly) that a person is suffering from insanity.:
  - His behavior became increasingly erratic, leading people to believe he was as mad as a hatter.

at the drop of a hat:
  Without any hesitation; instantly:
  - We're expected to just do it at the drop of a hat.

beat the (living) daylights out of SB:
  to physically attack one, as with punches and other blows, such that they suffer significant injury:
  - Our neighbor is in the hospital because a burglar beat the daylights out of him.
  - I'm worried that the captain of the football team will beat the living daylights out of me if he finds out that I'm secretly seeing his girlfriend.
  - Oh, my boyfriend knows that I would beat the living daylights out of him if he ever lies to me about something that serious.
  to defeat one decisively in a competition:
  - The final score was 17-1? Wow, we really beat the living daylights out of that team!

bereft:
  deprived of or lacking something, especially a nonmaterial asset:
  - Her room was stark and bereft of color.
  \(of a person\) lonely and abandoned, especially through someone's death or departure:
  - His death in 1990 left her bereft.

bite the bullet:
  to endure something necessary but unpleasant:
  - When no painkiller was available (in makeshift battlefield tents, for example), soldiers literally had to bite down on a bullet during surgical operations.

be black balled:
  to be voted against and denied membership:

bromide:
  a commonplace or tiresome person, bore:
  a commonplace or hackneyed statement or notion:
  - In many ways, he's an outlier on the self-help circuit. Thomas isn't selling shortcuts to success or feel-good bromides. He makes achievement sound grueling. His knack is for transforming those he meets — a CEO, an NBA All-Star, a guy manning the desk at a hotel — into the sort of person who loves digging deep and grinding hard.
  - Currently, Virginia's leaders are engaged in a tax debate over standard deductions for the middle class. Studying that problem would be a bromide that induces inertia. What is needed is action.

by (or in) leaps and bounds:
  with startlingly rapid progress:
  - FiiO’s own music app has also come in leaps and bounds and I would rate it close to HiBy Music in terms of ease of use but still lacking that killer DSP app like MSEB.
  - Productivity improved in leaps and bounds.

\(win\) by the skin of one's teeth:
  by a very narrow margin; barely:
  - I felt sleep all the times because I smoke to much joint. But thanks to the registered letter, sent to God everyday by mother, I could graduate by the skin of my teeth.

carbon copy:
  an exact copy:

carry the day:
  be victorious or successful:
  - Lacking good strategy in the battle, courage won’t carry the day.

chapfallen (a):
  cast down in spirit; depressed:
  - This season or next, don't bet on them turning a profit without making the playoffs. They need to do that next year to satisfy perennially chapfallen fans, if nothing else.

clairvoyance (n):
  the supposed faculty of perceiving things or events in the future or beyond normal sensory contact:
  - She stared at the card as if she could contact its writer by clairvoyance.
  - I am not a clairvoyant so I cannot tell what will happen in the next 6 months.

close, but no cigar:
  That's almost correct, but not quite:
  - It was close but no cigar for Johnny as he came second once again.

come to pass:
  happen; occur:
  - it came to pass that she had two sons
  - It came to pass that their love for each other grew and grew.

contrite:
  feeling or expressing remorse or penitence; affected by guilt:
  - On the dying bed, he made a very careful confession of his sins with a contrite heart.

conundrum:
  a confusing and difficult problem or question:
  - This is the confidence conundrum, where in order to be happy or loved or successful, first you need to be confident; but then to be confident, first you need to be happy or loved or successful.

coup de grace (n):
  a final blow or shot given to kill a wounded person or animal:
  - He administered the coup de grâce with a knife.
  an action or event that serves as the culmination of a bad or deteriorating situation:
  - The epidemic has been the coup de grâce for the airline crisis.

definitive (a):
  \(of a conclusion or agreement\) done or reached decisively and with authority:
  - a definitive diagnosis
  \(of a book or other text\) the most authoritative of its kind:
  - the definitive biography of Harry Truman.

denounce:
  publicly declare to be wrong or evil:
  - The Assembly denounced the use of violence.
  - He was widely denounced as a traitor.
  - Alexander is reported to have been reduced to laughter when Savonarola's denunciations were related to him.
  inform against:
  - Some of his own priests denounced him to the King for heresy.

discrepancy:
  a lack of compatibility or similarity between two or more facts:
  - There's a discrepancy between your account and his.

disenfranchise (v):
  deprive (someone) of the right to vote:
  - The law disenfranchised some 3,000 voters on the basis of a residence qualification.
  deprive (someone) of a right or privilege:
  - A measure that would disenfranchise people from access to legal advice
  - The catalyst for change will likely begin with Southeast Asia’s disenfranchised youth – younger populations that are now unemployed and tired of the region’s endemically ineffective governance.

dissolute:
  lax in morals; licentious:
  - No one was surprised by the news of Juan’s death. Everyone knew that he was a dissolute person and made a lot of enemies throughout his life. One of those could easily decide to take the matter to his own hand.

downplay (v):
  make (something) appear less important than it really is:
  - This report downplays the seriousness of global warming.

dress (up) to the nines:
  to dress buoyantly and high class”:
  - \"To the nines\" is an English idiom meaning "to perfection" or "to the highest degree".
  - She goes out dressed up to the nines and comes home after midnight.
  - Most of the photographs of her at her lowest weight show her dressed up to the nines for the runway.
  - Even a simple photo of themselves — pretty, proud, plump and dressed up to the nines — is enough to excite a strange moral response.

dystopia:
  \(a\) relating to or denoting an imagined place or state in which everything is unpleasant or bad, typically a totalitarian or environmentally degraded one:
  - the dystopian future of a society bereft of reason
  - the utopian dream that became a dystopian nightmare
  \(n\) a person who advocates or describes an imagined place or state in which everything is unpleasant or bad:
  - a lot of things those dystopians feared did not come true.

to eat humble pie:
  to admit your error and apologize:
  - After his candidate has lost the election, the boastful campaign manager had to eat humble pie.

effrontery (n):
  insolent or impertinent behavior:
  - One juror had the effrontery to challenge the coroner's decision.

elucidate:
  make (something) clear; explain:
  - In The Prince, Machiavelli uses Borgia as an example to elucidate the dangers of acquiring a principality by virtue of another.
  - In what follows I shall try to elucidate what I believe the problems to be.

encroach (v):
  \(usually encroach on/upon\) intrude on (a person's territory or a thing considered to be a right):
  - Encroachments by European aggressions left China powerless to control its own economic policies and led to the loss of Vietnam to France and Hong Kong to Britain.
  advance gradually beyond usual or acceptable limits:
  - The sea has encroached all around the coast.
  - The encroachment by the sea threatens the survival of the Morgan village.
