#!/usr/bin/env python3
'''Remove auto-created files'''

import argparse
import os
import shutil

junkFileList = [ '.DS_Store', '.wdmc', '.fseventsd', '.Spotlight-V100' ]

def process_file( filename, verbose=False):
    '''
    Delete junk files (mac os).
    Return True if deleted; otherwise, False
    '''

    # Extract only the filename or directory name from the absolute path
    basename = os.path.basename( filename )
    if basename in junkFileList:
        if os.path.isdir( filename ):
            shutil.rmtree( filename )
        else:
            os.remove( filename )

        if verbose:
            print( f'Removed {basename}' )

        return True

    return False

def main():
    '''The main function'''
    parser = argparse.ArgumentParser( description='Remove all junk files' )
    parser.add_argument( '-v', '--verbose', action='store_true', dest='verbose',
                         help='Print log messages' )
    parser.add_argument( 'folder', action='store', help='Folder to be cleaned' )
    args = parser.parse_args()

    folder = args.folder if not None else '.'

    # Walk the directory tree. It is actually a tuple of ( root, dirs, files )
    # But we don't use dirs here.
    for root, _, files in os.walk( folder, topdown=False ):
        for file in files:
            filename = os.path.join( root, file )
            process_file( filename, verbose=args.verbose )

if __name__ == '__main__':
    main()
