#!/usr/bin/env python
import argparse
import os
import sys
from debuglib import t0, setDebugLevel
from filelib import deleteJunkFiles

def main():
    reload( sys )
    sys.setdefaultencoding( 'utf-8' )

    parser = argparse.ArgumentParser( version='1.0',
            description='cleanJunkFiles parser' )
    parser.add_argument( '-B', '--debugLevel', action='store', dest='debugLevel',
            type=int, help='Set debug level' ) 
    parser.add_argument( 'folder', action='store', help='Folder to be cleaned' )
    args = parser.parse_args()
    assert args.folder

    if args.debugLevel:
        setDebugLevel( args.debugLevel )
        t0( "Set debugLevel to ", args.debugLevel )
        t0()
    
    for root, dirs, files in os.walk( args.folder, topdown=False ):
        for f in files:
            filename = os.path.join( root, f )
            if deleteJunkFiles( filename ):
                t0( '%s removed' % filename )

if __name__ == '__main__':
    main()
