#!/usr/bin/env bash

name=finreport
packages="PyPDF2 tabulate"
statements="/Users/athichart/Google Drive/My Drive/Document/Statements/2023"

workspace=$HOME/Workspace
script_dir=$workspace/scripts
venv_dir=$workspace/python_venv/$name

if [ ! -d "$venv_dir" ]
then
   echo "Preparing $venv_dir"
   python3 -m venv $venv_dir
   source $venv_dir/bin/activate
   python3 -m pip install $packages
   deactivate
fi

source $venv_dir/bin/activate
$script_dir/$name.py -l "$statements" "$@"
deactivate
