#!/usr/bin/env bash

name=finreport
packages="tabulate"

workspace=$HOME/Workspace
script_dir=$workspace/scripts
venv_dir=$workspace/python_venv/$name
statements="$workspace/credit_card_statements"

if [ ! -d "$venv_dir" ]
then
   echo "Preparing $venv_dir"
   python3 -m venv $venv_dir
   source $venv_dir/bin/activate
   python3 -m pip install $packages
   deactivate
fi

source $venv_dir/bin/activate
$script_dir/$name.py -l $statements
deactivate
