#!/usr/bin/env bash

name=flac2mp3
packages="pydub"

workspace=$HOME/Workspace
script_dir=$workspace/scripts
venv_dir=$workspace/python_venv/$name

if [ ! -d "$venv_dir" ]
then
   echo "Preparing $venv_dir"
   python3 -m venv $venv_dir
   source $venv_dir/bin/activate
   python3 -m pip install $packages
   deactivate
fi

if ! which ffmpeg > /dev/null; then
   echo "Installing ffmpeg"
   brew install ffmpeg
fi

source $venv_dir/bin/activate
$script_dir/$name.py "$@"
deactivate
