#!/usr/bin/env bash
# Monitor changes to a Linux filesystem. It is not working on MacOs.
#
# Reference:
# https://www.tecmint.com/pyinotify-monitor-filesystem-directory-changes-in-linux/

name=fmonitor
packages="pyinotify"

workspace=$HOME/Workspace
venv_dir=$workspace/python_venv/$name
script_dir="$(dirname "$(readlink -f "$0")")"

if [ ! -d "$venv_dir" ]
then
   echo "Preparing $venv_dir"
   python3 -m venv $venv_dir
   source $venv_dir/bin/activate
   python3 -m pip install $packages
   deactivate
fi

if [ $# -eq 0 ]
then
   echo "usage: $name <folder>"
   exit
fi

source $venv_dir/bin/activate
python -m pyinotify -v "$1"
deactivate
