#!/usr/bin/env bash

workspace=$HOME/Workspace

# python3 -m venv pdfmgr
# source $workspace/python_venv/pdfmgr/bin/activate
# python3 -m pip install PyPDF2
# deactivate

source $workspace/python_venv/pdfmgr/bin/activate
python3 $workspace/scripts/pdfmgr.py "$@"
deactivate
