#!/usr/bin/env bash

workspace=$HOME/Workspace

# To create a new virtual environment:
# python3 -m venv portmgr
# source $workspace/python_venv/portmgr/bin/activate
# python3 -m pip install iptcinfo3
# python3 -m pip install Pillow
# deactivate

source $workspace/python_venv/portmgr/bin/activate
python3 $workspace/scripts/portmgr.py "$@" | grep -v "WARNING: problems with charset recognition"
deactivate
