#!/usr/bin/env bash
# To create a new virtual environment:
# python3 -m venv portMgr
# source $workspace/python_venv/portMgr/bin/activate
# python3 -m pip install iptcinfo3
# python3 -m pip install Pillow
# deactivate

workspace=/Users/athichart/Workspace
source $workspace/python_venv/portMgr/bin/activate
python3 $workspace/scripts/portMgr.py "$@"
deactivate
