#!/usr/bin/env bash
#
# To create a new virtual environment:
# python3 -m venv portmgr
# source $workspace/python_venv/portmgr/bin/activate
# python3 -m pip install iptcinfo3
# python3 -m pip install Pillow
# deactivate

workspace=/Users/athichart/Workspace
source $workspace/python_venv/portmgr/bin/activate
python3 $workspace/scripts/portmgr.py "$@" | grep -v "WARNING: problems with charset recognition"
deactivate
