#!/usr/bin/env bash

name=quote
packages="colorama"

workspace=$HOME/Workspace
venv_dir=$workspace/python_venv/$name
script_dir="$(dirname "$(readlink -f "$0")")"

if [ ! -d "$venv_dir" ]
then
   echo "Preparing $venv_dir"
   python3 -m venv $venv_dir
   source $venv_dir/bin/activate
   python3 -m pip install $packages
   deactivate
fi

source $venv_dir/bin/activate
$script_dir/$name.py "$@"
deactivate
